atcoder:
  user_id: Ryoga_exe
  last_update: 0
extensions:
  COBOL - Fixed: cob
  IOI-Style C++: cpp
  COBOL - Free: cob
  Visual Basic: vb
  Common Lisp: lsp
  Objective-C: mm
  Standard ML: ml
  Haxe; Java: hx
  JavaScript: js
  MoonScript: moon
  TypeScript: ts
  Brainfuck: bf
  Haxe; js: hs
  Unlambda: unl
  Clojure: click
  Crystal: coq
  Fortran: f08
  Haskell: hs
  OCaml: ml
  Ceylon: ceylon
  Cython: cy
  Elixir: e
  Erlang: em
  Kotlin: kt
  LuaJIT: lua
  Octave: m
  Pascal: pas
  Prolog: pl
  Python: py
  Racket: rkt
  Scheme: scm
  Forth: FORTH
  Julia: jl
  Scala: scala
  Swift: swift
  Bash: sh
  Dart: dart
  Dash: sh
  Java: java
  JAVA: java
  Perl: pl
  PyPy: py
  Raku: raku
  Ruby: rb
  Rust: rs
  Text: txt
  Ada: ada
  Awk: awk
  C++: cpp
  Lua: lua
  Nim: nim
  PHP: php
  Sed: sed
  Vim: vim
  Zsh: sh
  C#: cs
  F#: fs
  Go: go
  bc: bc
  dc: dc
  C: c
  D: d
